/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;

import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import java.util.List;

/**
 *
 * @author ruanr
 */
public class EnviaNotificacaoView extends javax.swing.JInternalFrame {

    private JList<String> usuariosList;
    private DefaultListModel<String> listModel;
    private JTextField campoBusca;
    private JButton btnBuscar;

    /**
     * Creates new form EnviaNotificacaoView
     */
    public EnviaNotificacaoView() {
        initComponents();
        adicionarComponentesAdicionais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotificacao = new javax.swing.JLabel();
        txtTextoNotificacao = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        lblNotificacao.setText("Digite uma notificação/mensagem para enviar aos usuários");

        txtTextoNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextoNotificacaoActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar notificação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnviar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtTextoNotificacao))
                        .addComponent(lblNotificacao)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblNotificacao)
                .addGap(18, 18, 18)
                .addComponent(txtTextoNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEnviar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void adicionarComponentesAdicionais() {
        // Criar painel de busca
        JPanel panelBusca = new JPanel();
        campoBusca = new JTextField(20);
        btnBuscar = new JButton("Buscar");
        panelBusca.add(new JLabel("Buscar usuários:"));
        panelBusca.add(campoBusca);
        panelBusca.add(btnBuscar);

        // Criar lista de usuários
        listModel = new DefaultListModel<>();
        usuariosList = new JList<>(listModel);
        usuariosList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JScrollPane scrollPane = new JScrollPane(usuariosList);

        // Adicionar label de instrução
        JLabel lblInstrucao = new JLabel("Aperte Ctrl + mouse para selecionar mais de um usuário");

        // Obter o layout existente
        GroupLayout layout = (GroupLayout) getContentPane().getLayout();

        // Adicionar componentes ao layout existente
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(panelBusca)
                        .addComponent(lblInstrucao)
                        .addComponent(scrollPane)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnEnviar)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(txtTextoNotificacao))
                                                .addComponent(lblNotificacao)))
                                .addGap(0, 29, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelBusca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInstrucao)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNotificacao)
                                .addGap(18, 18, 18)
                                .addComponent(txtTextoNotificacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnEnviar)
                                .addContainerGap())
        );

        pack();
    }
private void txtTextoNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextoNotificacaoActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoNotificacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblNotificacao;
    private javax.swing.JTextField txtTextoNotificacao;
    // End of variables declaration//GEN-END:variables

    public JList<String> getUsuariosList() {
        return usuariosList;
    }

    public void atualizarListaUsuarios(java.util.List<String> usuarios) {
        listModel.clear();
        for (String usuario : usuarios) {
            listModel.addElement(usuario);
        }
    }

    public JTextField getCampoBusca() {
        return campoBusca;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void exibirMensagem(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem);
    }

    /**
     * @return the btnEnviar
     */
    public javax.swing.JButton getBtnEnviar() {
        return btnEnviar;
    }

    /**
     * @return the txtTextoNotificacao
     */
    public javax.swing.JTextField getTxtTextoNotificacao() {
        return txtTextoNotificacao;
    }

    /**
     * @param txtTextoNotificacao the txtTextoNotificacao to set
     */
    public void setTxtTextoNotificacao(javax.swing.JTextField txtTextoNotificacao) {
        this.txtTextoNotificacao = txtTextoNotificacao;
    }

    // Add a new method to get selected users
    public List<String> getSelectedUsers() {
        return usuariosList.getSelectedValuesList();
    }

}
