/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JOptionPane;

import Presenter.BuscarPresenter;
import Presenter.ManterInclusaoEdicaoPresenter;
import config.AppInitializer;
/**
 *
 * @author rauni
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    public javax.swing.JMenuItem getMenuAdicionarEditar() {
        return AdicionarEditar;
    }
    public javax.swing.JMenuItem getMenuBuscar() {
        return Buscar;
    }
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaPrincipalView = new javax.swing.JDesktopPane();
        lblTipoUsuario = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNotificacao = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        Buscar = new javax.swing.JMenuItem();
        AdicionarEditar = new javax.swing.JMenuItem();
        config = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipoUsuario.setDisplayedMnemonic('l');
        lblTipoUsuario.setText("Tipo: N/A");
        lblTipoUsuario.setPreferredSize(new java.awt.Dimension(120, 40));

        lblLogin.setDisplayedMnemonic('l');
        lblLogin.setText("Usuário não logado");
        lblLogin.setPreferredSize(new java.awt.Dimension(140, 40));

        lblNotificacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16px bell.png"))); // NOI18N
        lblNotificacao.setText("0");
        lblNotificacao.setPreferredSize(new java.awt.Dimension(70, 40));

        TelaPrincipalView.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPrincipalView.setLayer(lblLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPrincipalView.setLayer(lblNotificacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaPrincipalViewLayout = new javax.swing.GroupLayout(TelaPrincipalView);
        TelaPrincipalView.setLayout(TelaPrincipalViewLayout);
        TelaPrincipalViewLayout.setHorizontalGroup(
            TelaPrincipalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalViewLayout.createSequentialGroup()
                .addGap(880, 880, 880)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TelaPrincipalViewLayout.setVerticalGroup(
            TelaPrincipalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalViewLayout.createSequentialGroup()
                .addGap(750, 750, 750)
                .addGroup(TelaPrincipalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Menu");

        Buscar.setMnemonic('o');
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        fileMenu.add(Buscar);

        AdicionarEditar.setText("Adicionar ou Editar");
        AdicionarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarEditarActionPerformed(evt);
            }
        });
        fileMenu.add(AdicionarEditar);

        config.setText("Configurações");
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });
        fileMenu.add(config);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipalView)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipalView)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        BuscarView buscar = new BuscarView();
        TelaPrincipalView.add(buscar);
        buscar.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    private void AdicionarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarEditarActionPerformed
        ManterInclusaoEdicaoView manter = new ManterInclusaoEdicaoView();
        TelaPrincipalView.add(manter);
        manter.setVisible(true);
    }//GEN-LAST:event_AdicionarEditarActionPerformed

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        JOptionPane.showMessageDialog(this, "Configuração menu clicked");
        AppInitializer config = new AppInitializer();
        
    }//GEN-LAST:event_configActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarEditar;
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JDesktopPane TelaPrincipalView;
    private javax.swing.JMenuItem config;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNotificacao;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the lblLogin
     */
    public javax.swing.JLabel getLblLogin() {
        return lblLogin;
    }

    /**
     * @return the lblNotificacao
     */
    public javax.swing.JLabel getLblNotificacao() {
        return lblNotificacao;
    }

    /**
     * @return the lblTipoUsuario
     */
    public javax.swing.JLabel getLblTipoUsuario() {
        return lblTipoUsuario;
    }
     public void exibirMensagem(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem);
    }
    public void atualizarInformacoesUsuario(String nomeUsuario, String tipoUsuario) {
        lblLogin.setText("Usuário: " + nomeUsuario);
        lblTipoUsuario.setText("Tipo: " + tipoUsuario);
    }
    public void atualizarContadorNotificacoes(int quantidade) {
        lblNotificacao.setText(String.valueOf(quantidade));
    }
    public void habilitarMenuAdministrador(boolean habilitar) {
        AdicionarEditar.setEnabled(habilitar);
        Buscar.setEnabled(habilitar);
    }
    public String solicitarNomeUsuario() {
        return JOptionPane.showInputDialog(this, "Digite seu nome de usuário:");
    }
    public String solicitarSenha() {
        return JOptionPane.showInputDialog(this, "Digite sua senha:");
    }
    public void fecharTela() {
        dispose();
    }
    public void exibirTela() {
        setVisible(true);
    }
}
