/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

import Presenter.BuscarPresenter;
import Presenter.ManterInclusaoEdicaoPresenter;
import config.AppInitializer;

/**
 *
 * @author rauni
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public javax.swing.JMenu getMenuAdicionarEditar() {
        return menuAdicionarEditar;
    }
    public javax.swing.JMenu getMenuBuscar() {
        return menuBuscar;
    }
    public TelaPrincipalView() {
        initComponents();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoUsuario = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNotificacao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBuscar = new javax.swing.JMenu();
        menuAdicionarEditar = new javax.swing.JMenu();
        menuConfig = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipoUsuario.setDisplayedMnemonic('l');
        lblTipoUsuario.setText("Tipo: N/A");

        lblLogin.setDisplayedMnemonic('l');
        lblLogin.setText("Usuário não logado");

        lblNotificacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16px bell.png"))); // NOI18N
        lblNotificacao.setText("0");

        menuBuscar.setText("Buscar");
        menuBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBuscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBuscar);

        menuAdicionarEditar.setText("Adicioanar/Editar");
        menuAdicionarEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdicionarEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAdicionarEditar);

        menuConfig.setText("Configuracão");
        menuConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConfigMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(lblLogin)
                .addGap(18, 18, 18)
                .addComponent(lblTipoUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(lblLogin)
                    .addComponent(lblNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 
    private void menuBuscarMouseClicked(java.awt.event.MouseEvent evt) {
        var presenter = new BuscarPresenter();
    }

    private void menuAdicionarEditarMouseClicked(java.awt.event.MouseEvent evt) {
        var presenter = new ManterInclusaoEdicaoPresenter(AppInitializer.getRepositorioUsuarios());
    }

    private void menuConfigMouseClicked(java.awt.event.MouseEvent evt) {
        // Add your configuration logic here
        JOptionPane.showMessageDialog(this, "Configuração menu clicked");
    }

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNotificacao;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenu menuAdicionarEditar;
    private javax.swing.JMenu menuBuscar;
    private javax.swing.JMenu menuConfig;
    // End of variables declaration//GEN-ENDIFICATIONS

    /**
     * @return the lblLogin
     */
    public javax.swing.JLabel getLblLogin() {
        return lblLogin;
    }

    /**
     * @return the lblNotificacao
     */
    public javax.swing.JLabel getLblNotificacao() {
        return lblNotificacao;
    }

    /**
     * @return the lblTipoUsuario
     */
    public javax.swing.JLabel getLblTipoUsuario() {
        return lblTipoUsuario;
    }
     public void exibirMensagem(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem);
    }
    public void atualizarInformacoesUsuario(String nomeUsuario, String tipoUsuario) {
        lblLogin.setText("Usuário: " + nomeUsuario);
        lblTipoUsuario.setText("Tipo: " + tipoUsuario);
    }
    public void atualizarContadorNotificacoes(int quantidade) {
        lblNotificacao.setText(String.valueOf(quantidade));
    }
    public void habilitarMenuAdministrador(boolean habilitar) {
        menuAdicionarEditar.setEnabled(habilitar);
        menuBuscar.setEnabled(habilitar);
    }
    public String solicitarNomeUsuario() {
        return JOptionPane.showInputDialog(this, "Digite seu nome de usuário:");
    }
    public String solicitarSenha() {
        return JOptionPane.showInputDialog(this, "Digite sua senha:");
    }
    public void fecharTela() {
        dispose();
    }
    public void exibirTela() {
        setVisible(true);
    }
}
